---
title: "Results paper 1"
author: "Alejandro Muñoz Escribano"
format: html
editor: visual
---

```{r setup, include=FALSE}

library(tidyverse)
library(glmmTMB)
library(emmeans)
library(DHARMa)
library(performance)
library(car)
library (visreg)
here::i_am("docs/Results.qmd")
```

# Lisso abundance

## With field 5

```{r Lisso dataframe, include=FALSE}
Lisso <- read.csv2(here::here("data/modified/Lisso_abundance.csv")) %>% 
  mutate(Date = as.factor(Date),
         Field = as.factor(Field),
         Treatment = as.factor(Treatment))

model.lisso <- glmmTMB(Abundance ~ Treatment*Date + (1|Field), data = Lisso, family = poisson)
```

**Model formula:**

```{r Lisso model, output=FALSE}
glmmTMB(Abundance ~ Treatment*Date + (1|Field), data = Lisso, family = poisson)
```

**Summary:**

```{r Lisso summary, echo=FALSE}
summary(model.lisso)
r2(model.lisso)
Anova(model.lisso, type = 3)
```

**Model diagnostics:**

```{r Lisso model diagnostics, echo=FALSE}
dharma <- simulateResiduals(model.lisso, plot = T)
```

**Estimated marginal means plots:**

Factor treatment

```{r Lisso emmeans 1, echo=FALSE, message=FALSE}
emmeans(model.lisso, pairwise~Treatment, type = "response")

lisso_emm <- as.data.frame(emmeans(model.lisso, pairwise ~ Treatment, type = "response")$emmeans)
ggplot(lisso_emm, aes(x = Treatment, y = rate)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = rate-SE, ymax = rate+SE), width = 0.2) +
  labs(x = "Treatment", y = "Estimated Marginal Mean of Abundance") +
  theme_minimal()
```

Factor treatment\*date

```{r Lisso emmeans 2, echo=FALSE, message=FALSE}
emmeans(model.lisso, pairwise~Treatment|Date, type = "response")

lisso_emm.2 <- as.data.frame(emmeans(model.lisso, pairwise ~ Treatment|Date, type = "response")$emmeans)
ggplot(lisso_emm.2, aes(x = Date, y = rate, color = Treatment)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = rate-SE, ymax = rate+SE), width = 0.2) +
  labs(x = "Date", y = "Estimated Marginal Mean of Abundance") +
  theme_minimal()
```

**Figure:**

```{r Lisso figure treatment, echo=FALSE}
pd_jitter <- position_jitter(width = 0.07, height = 0)
pd_dodge  <- position_dodge(width = 0.15)
pal_cb <- c(
  "#0072B2", # azul
  "#D55E00", # rojo/naranja
  "#009E73", # verde
  "#CC79A7", # morado
  "#E69F00"  # amarillo/naranja
)

lisso_summ <- Lisso %>% 
  group_by(Field, Treatment) %>% 
  summarise(mean_dmg = mean(Abundance),
            sd = sd(Abundance, na.rm = TRUE),
            n = sum(!is.na(Abundance)),
            se = sd / sqrt(n),
            .groups = "drop"
  )

#Plot
ggplot() +
  geom_jitter(
    data = Lisso,
    aes(x = Treatment, y = Abundance, color = as.factor(Field)),
    width = 0.07, height = 0,
    alpha = 0.30, size = 2.5
  ) +
  geom_line(
    data = lisso_summ,
    aes(x = Treatment, y = mean_dmg, group = as.factor(Field), color = as.factor(Field)),
    linewidth = 0.9, alpha = 0.5
  ) +
  geom_point(
    data = lisso_summ,
    aes(x = Treatment, y = mean_dmg, color = as.factor(Field)),
    size = 4,
    alpha = 0.5
  ) +
  
  #Global emmean layer
  geom_line(
    data = lisso_emm,
    aes(x = Treatment, y = rate, group = 1),
    inherit.aes = FALSE,
    linewidth = 1.6,
    color = "black"
  ) +
  
  geom_errorbar(
    data = lisso_emm,
    aes(x = Treatment,
        ymin = rate-SE,
        ymax = rate+SE,
        group = 1),
    inherit.aes = FALSE,
    width = 0.08,
    linewidth = 1.1,
    color = "black"
  ) +
  
  geom_point(
    data = lisso_emm,
    aes(x = Treatment, y = rate),
    inherit.aes = FALSE,
    size = 4.8,
    shape = 21,
    fill = "white",
    color = "black",
    stroke = 1.2
  ) +
  scale_x_discrete(labels = c("BE" = "No", "FO" = "Yes")) +
  scale_color_manual(values = pal_cb, name = "Field") +
  labs(
    x = "Birds",
    y = "Adult abundance",
  ) +
  theme_minimal(base_size = 14)
```

Factor treatment*date

```{r Lisso figure date, echo=FALSE}
lisso_summ_date <- Lisso %>% 
  group_by(Field, Treatment, Date) %>% 
  summarise(mean_dmg = mean(Abundance),
            sd = sd(Abundance, na.rm = TRUE),
            n = sum(!is.na(Abundance)),
            se = sd / sqrt(n),
            .groups = "drop"
  )


ggplot() +
  geom_jitter(
    data = Lisso,
    aes(x = Treatment, y = Abundance, color = as.factor(Field)),
    width = 0.07, height = 0,
    alpha = 0.30, size = 2.5
  ) +
  geom_line(
    data = lisso_summ_date,
    aes(x = Treatment, y = mean_dmg, group = as.factor(Field), color = as.factor(Field)),
    linewidth = 0.9, alpha = 0.5
  ) +
  geom_point(
    data = lisso_summ_date,
    aes(x = Treatment, y = mean_dmg, color = as.factor(Field)),
    size = 4,
    alpha = 0.5
  ) +
  facet_wrap(~Date) +
  
  
  #Global emmean layer
  
  geom_line(
    data = lisso_emm.2,
    aes(x = Treatment, y = rate, group = 1),
    inherit.aes = FALSE,
    linewidth = 1.6,
    color = "black"
  ) +
  
  geom_errorbar(
    data = lisso_emm.2,
    aes(x = Treatment,
        ymin = rate-SE,
        ymax = rate+SE,
        group = 1),
    inherit.aes = FALSE,
    width = 0.08,
    linewidth = 1.1,
    color = "black"
  ) +
  
  geom_point(
    data = lisso_emm.2,
    aes(x = Treatment, y = rate),
    inherit.aes = FALSE,
    size = 4.8,
    shape = 21,
    fill = "white",
    color = "black",
    stroke = 1.2
  ) +
  scale_x_discrete(labels = c("BE" = "No", "FO" = "Yes")) +
  scale_color_manual(values = pal_cb, name = "Field") +
  labs(
    x = "Birds",
    y = "Abundancia de adultos",
  ) +
  theme_minimal(base_size = 14)
```


------------------------------------------------------------------------

## Without field 5

```{r Lisso dataframe no-5, include=FALSE}
Lisso_no5<- Lisso %>% 
  filter (Field != "5")

model.lisso.no5 <- glmmTMB(Abundance ~ Treatment*Date + (1|Field), data = Lisso_no5, family = poisson)

```

**Summary:**

```{r Lisso summary no-5, echo=FALSE}
summary(model.lisso.no5)

r2(model.lisso.no5)

Anova(model.lisso.no5, type = 3)
```

**Model diagnostics:**

```{r Lisso model diagnostics no-5, echo=FALSE}
dharma <- simulateResiduals(model.lisso.no5, plot = T)
```

**Estimated marginal means plots:**

Factor treatment

```{r Lisso emmeans 1 no-5, echo=FALSE, message=FALSE}
emmeans(model.lisso.no5, pairwise~Treatment, type = "response")

lisso.no5_emm <- as.data.frame(emmeans(model.lisso.no5, pairwise ~ Treatment, type = "response")$emmeans)
ggplot(lisso.no5_emm, aes(x = Treatment, y = rate)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = rate-SE, ymax = rate+SE), width = 0.2) +
  labs(x = "Treatment", y = "Estimated Marginal Mean of Abundance") +
  theme_minimal()
```

Factor treatment\*date

```{r Lisso emmeans 2 no-5, echo=FALSE, message=FALSE}
emmeans(model.lisso.no5, pairwise~Treatment|Date, type = "response")

lisso.no5_emm.2 <- as.data.frame(emmeans(model.lisso.no5, pairwise ~ Treatment|Date, type = "response")$emmeans)
ggplot(lisso.no5_emm.2, aes(x = Date, y = rate, color = Treatment)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = rate-SE, ymax = rate+SE), width = 0.2) +
  labs(x = "Date", y = "Estimated Marginal Mean of Abundance") +
  theme_minimal()
```

**Figure:**

Factor treatment

```{r Lisso figure treatment no-5, echo=FALSE}

lisso.no5_summ <- Lisso_no5 %>% 
  group_by(Field, Treatment) %>% 
  summarise(mean_dmg = mean(Abundance),
            sd = sd(Abundance, na.rm = TRUE),
            n = sum(!is.na(Abundance)),
            se = sd / sqrt(n),
            .groups = "drop"
  )

#Plot
ggplot() +
  geom_jitter(
    data = Lisso_no5,
    aes(x = Treatment, y = Abundance, color = as.factor(Field)),
    width = 0.07, height = 0,
    alpha = 0.30, size = 2.5
  ) +
  geom_line(
    data = lisso.no5_summ,
    aes(x = Treatment, y = mean_dmg, group = as.factor(Field), color = as.factor(Field)),
    linewidth = 0.9, alpha = 0.5
  ) +
  geom_point(
    data = lisso.no5_summ,
    aes(x = Treatment, y = mean_dmg, color = as.factor(Field)),
    size = 4,
    alpha = 0.5
  ) +
  
  #Global emmean layer
  geom_line(
    data = lisso.no5_emm,
    aes(x = Treatment, y = rate, group = 1),
    inherit.aes = FALSE,
    linewidth = 1.6,
    color = "black"
  ) +
  
  geom_errorbar(
    data = lisso.no5_emm,
    aes(x = Treatment,
        ymin = rate-SE,
        ymax = rate+SE,
        group = 1),
    inherit.aes = FALSE,
    width = 0.08,
    linewidth = 1.1,
    color = "black"
  ) +
  
  geom_point(
    data = lisso.no5_emm,
    aes(x = Treatment, y = rate),
    inherit.aes = FALSE,
    size = 4.8,
    shape = 21,
    fill = "white",
    color = "black",
    stroke = 1.2
  ) +
  scale_x_discrete(labels = c("BE" = "No", "FO" = "Yes")) +
  scale_color_manual(values = pal_cb, name = "Field") +
  labs(
    x = "Birds",
    y = "Adult abundance",
  ) +
  theme_minimal(base_size = 14)
```

Factor treatment*date

```{r Lisso figure date no-5, echo=FALSE}

lisso.no5_summ_date <- Lisso_no5 %>% 
  group_by(Field, Treatment, Date) %>% 
  summarise(mean_dmg = mean(Abundance),
            sd = sd(Abundance, na.rm = TRUE),
            n = sum(!is.na(Abundance)),
            se = sd / sqrt(n),
            .groups = "drop"
  )

#Plot
ggplot() +
  geom_jitter(
    data = Lisso_no5,
    aes(x = Treatment, y = Abundance, color = as.factor(Field)),
    width = 0.07, height = 0,
    alpha = 0.30, size = 2.5
  ) +
  geom_line(
    data = lisso.no5_summ_date,
    aes(x = Treatment, y = mean_dmg, group = as.factor(Field), color = as.factor(Field)),
    linewidth = 0.9, alpha = 0.5
  ) +
  geom_point(
    data = lisso.no5_summ_date,
    aes(x = Treatment, y = mean_dmg, color = as.factor(Field)),
    size = 4,
    alpha = 0.5
  ) +
  facet_wrap(~Date) +
  
  #Global emmean layer
  geom_line(
    data = lisso.no5_emm.2,
    aes(x = Treatment, y = rate, group = 1),
    inherit.aes = FALSE,
    linewidth = 1.6,
    color = "black"
  ) +
  
  geom_errorbar(
    data = lisso.no5_emm.2,
    aes(x = Treatment,
        ymin = rate-SE,
        ymax = rate+SE,
        group = 1),
    inherit.aes = FALSE,
    width = 0.08,
    linewidth = 1.1,
    color = "black"
  ) +
  
  geom_point(
    data = lisso.no5_emm.2,
    aes(x = Treatment, y = rate),
    inherit.aes = FALSE,
    size = 4.8,
    shape = 21,
    fill = "white",
    color = "black",
    stroke = 1.2
  ) +
  scale_x_discrete(labels = c("BE" = "No", "FO" = "Yes")) +
  scale_color_manual(values = pal_cb, name = "Field") +
  labs(
    x = "Birds",
    y = "Adult abundance",
  ) +
  theme_minimal(base_size = 14)
```



# Leaf damage
